### ISSUE TITLE
write unittests for all functions and methods

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#23]
EDIT 2022-11-30: updated check list from coverage report, see below for original list

- r5/regional_task.py
    - [ ] 505
- r5/transit_layer.py
    - [ ] 90
- util/data_validation.py
    - [ ] 30
- util/jvm.py
    - [ ] 55
- util/memory_footprint.py
    - [ ] 33

```
- [ ] r5/regional_task.py:class RegionalTask:
- [ ] r5/regional_task.py:    def __init__(
- [ ] r5/regional_task.py:    def access_modes(self):
- [ ] r5/regional_task.py:    def access_modes(self, access_modes):
- [ ] r5/regional_task.py:    def departure(self):
- [ ] r5/regional_task.py:    def departure(self, departure):
- [ ] r5/regional_task.py:    def departure_time_window(self):
- [ ] r5/regional_task.py:    def departure_time_window(self, departure_time_window):
- [ ] r5/regional_task.py:    def destinations(self):
- [ ] r5/regional_task.py:    def destinations(self, destinations):
- [ ] r5/regional_task.py:    def egress_modes(self):
- [ ] r5/regional_task.py:    def egress_modes(self, egress_modes):
- [ ] r5/regional_task.py:    def max_bicycle_traffic_stress(self):
- [ ] r5/regional_task.py:    def max_bicycle_traffic_stress(self, max_bicycle_traffic_stress):
- [ ] r5/regional_task.py:    def max_public_transport_rides(self):
- [ ] r5/regional_task.py:    def max_public_transport_rides(self, max_public_transport_rides):
- [ ] r5/regional_task.py:    def max_time(self):
- [ ] r5/regional_task.py:    def max_time(self, max_time):
- [ ] r5/regional_task.py:    def max_time_cycling(self):
- [ ] r5/regional_task.py:    def max_time_cycling(self, max_time_cycling):
- [ ] r5/regional_task.py:    def max_time_driving(self):
- [ ] r5/regional_task.py:    def max_time_driving(self, max_time_driving):
- [ ] r5/regional_task.py:    def max_time_walking(self):
- [ ] r5/regional_task.py:    def max_time_walking(self, max_time_walking):
- [ ] r5/regional_task.py:    def percentiles(self):
- [ ] r5/regional_task.py:    def percentiles(self, percentiles):
- [ ] r5/regional_task.py:    def origin(self):
- [ ] r5/regional_task.py:    def origin(self, origin):
- [ ] r5/regional_task.py:    def scenario(self):
- [ ] r5/regional_task.py:    def scenario(self, scenario):
- [ ] r5/regional_task.py:    def speed_cycling(self):
- [ ] r5/regional_task.py:    def speed_cycling(self, speed_cycling):
- [ ] r5/regional_task.py:    def speed_walking(self):
- [ ] r5/regional_task.py:    def speed_walking(self, speed_walking):
- [ ] r5/regional_task.py:    def transport_modes(self):
- [ ] r5/regional_task.py:    def transport_modes(self, transport_modes):
- [ ] r5/regional_task.py:    def _enum_set(values, java_class):
- [x] r5/breakdown_stat.py:class BreakdownStat(enum.Enum):
- [x] r5/transport_network.py:class TransportNetwork:
- [x] r5/transport_network.py:    def __init__(self, osm_pbf, gtfs=[], build_config={}):
- [x] r5/transport_network.py:    def from_directory()
- [x] r5/transport_network.py:    def linkage_cache(self):
- [x] r5/transport_network.py:    def street_layer(self):
- [x] r5/transport_network.py:    def timezone(self):
- [ ] r5/scenario.py:class Scenario:
- [ ] r5/scenario.py:    def __init__(self):
- [ ] r5/scenario.py:    def id(self):
- [x] r5/transit_mode.py:class TransitMode(enum.Enum):
- [x] r5/leg_mode.py:class LegMode(enum.Enum):
- [x] r5/travel_time_matrix.py:class TravelTimeMatrix:
- [x] r5/travel_time_matrix.py:    def __init__(
- [x] r5/travel_time_matrix.py:    def compute_travel_times(self):
- [x] r5/travel_time_matrix.py:    def _parse_results_of_one_origin_details(self, from_id, results):
- [x] r5/travel_time_matrix.py:    def _parse_results_of_one_origin_travel_times(self, from_id, results):
- [x] r5/travel_time_matrix.py:    def _travel_times_from_one_origin(self, from_id):
- [x] r5/street_mode.py:class StreetMode(enum.Enum):
- [ ] r5/transport_network_builder_config.py:class TransportNetworkBuilderConfig(dict):
- [ ] r5/transport_network_builder_config.py:    def __init__(self, **kwargs):
- [x] util/camel_to_snake_case.py:def camel_to_snake_case(camel_case):
- [x] util/contains_gtfs_data.py
- [x] util/memory_footprint.py:def share_of_ram(share=0.8, leave_at_least=(2 * (2 ** 10))):
- [x] util/memory_footprint.py:def max_memory(max_memory):
- [ ] util/config.py:def arguments():
- [x] util/snake_to_camel_case.py:def snake_to_camel_case(snake_case):
- [x] util/validatingrequestssession.py:class ValidatingRequestsSession(requests.Session):
- [x] util/validatingrequestssession.py:    def __init__(
- [ ] util/validatingrequestssession.py:    def get(self, url, checksum, **kwargs):
- [ ] util/validatingrequestssession.py:    def post(self, url, checksum, **kwargs):
- [ ] util/validatingrequestssession.py:    def request(self, method, url, checksum, **kwargs):
```

**Comment by christophfink** [comment]
wow, and I had forgotten that I had, indeed, written one (1) test :D

**Comment by HTenkanen** [comment]
When doing these, let's aim to do them in small chunks, so that the commit history will stay relatively clean.

**Comment by HTenkanen** [comment]
And we need to communicate who works on which one 🙂

**Comment by christophfink** [comment]
I just starting doing the lowest-hanging fruits: util/snake_to_camel_case and vice versa

**Comment by christophfink** [comment]
I’m now working in draft PR #73 , I put the checkmark before I start working on a test.

**Comment by christophfink** [comment]
TransportNetwork still needs some improvements:

```
# TODO: improve these tests to check whether the test data set
# is loaded correctly.

# Note that com.conveyal.r5.transit.TransportNetwork.checksum()
# is not consistent between runs (and sometimes also not between the
# two constructors, for some reason). Ideas how to test:
#  - count segments/nodes/etc in transport_network.street_layer
#  - count stops/routes/etc in ._transport_network.transitLayer()
```

**Comment by HTenkanen** [comment]
@christophfink : FYI: Adding tests now for `memory_footprint.py`

**Comment by christophfink** [comment]
> There's a sketched-out plan for testing the cacheing of the r5 jar in this pull request: [#92 (comment)](https://github.com/r5py/r5py/pull/92#issuecomment-1143945129)

> 1. import r5py.util.classpath
> 2. reload that module
> 3. check whether file was downloaded a second time.

**Comment by christophfink** [comment]
The remaining five lines, the only ones in their respective files, are a bit difficult to write tests for. I would suggest that maybe we call this issue resolved, as we are standing at 97-99% coverage, depending on how you count it. Feel free to re-open, if you disagree :) Even more so, feel free to try to tackle one of the remaining lines :)
